version: '2'

services:
    bolt:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./db-data:/var/www/html/app/database
            - ./files:/var/www/html/public/files
            - ./extensions:/var/www/html/extensions
            - ./config:/var/www/html/app/config
            - ./theme:/var/www/html/public/theme
            - ./php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        ports:
            - "127.0.0.1:8000:80"
        env_file:
            - bolt.env
        links:
            - mariadb
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}

    mariadb:
        image: mariadb:latest
        restart: always
        env_file:
            - mariadb.env
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    adminer:
        image: dockette/adminer:mysql
        restart: always
        ports:
            - "127.0.0.1:8008:80"