version: '2'

services:
    bolt:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./db-data:/var/www/html/app/database
            - ./files:/var/www/html/public/files
            - ./extensions:/var/www/html/extensions
            - ./config:/var/www/html/app/config
            - ./theme:/var/www/html/public/theme
        ports:
            - "127.0.0.1:8000:80"
        env_file:
            - bolt.env
        links:
        - mariadb
    mariadb:
        image: mariadb:latest
        restart: always
        env_file:
            - mariadb.env
