version: '2'

services:
    bolt:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./app/db-data:/var/www/html/app/database
            - ./app/files:/var/www/html/public/files
            - ./app/extensions:/var/www/html/extensions
            - ./app/config:/var/www/html/app/config
            - ./app/theme:/var/www/html/public/theme
            - ./config/php.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./config/bolt_config_local.yml:/var/www/html/app/config/config_local.yml
        ports:
            - "127.0.0.1:8000:80"
        env_file:
            - config/bolt.env
    adminer:
        image: dockette/adminer:full
        restart: always
        ports:
            - "127.0.0.1:8008:80"