version: '2'

services:
    bolt:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./app/db-data:/var/www/html/app/database
            - ./app/files:/var/www/html/public/files
            - ./app/extensions:/var/www/html/extensions
            - ./app/config:/var/www/html/app/config
            - ./app/theme:/var/www/html/public/theme
            - ./config/php.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./config/bolt_config_local.yml:/var/www/html/app/config/config_local.yml
        ports:
            - "127.0.0.1:8000:80"
        env_file:
            - config/bolt.env
        links:
            - mariadb
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}

    mariadb:
        image: mariadb:latest
        restart: always
        env_file:
            - config/mariadb.env
        volumes:
            - ./app/mysql:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    adminer:
        image: dockette/adminer:mysql
        restart: always
        ports:
            - "127.0.0.1:8008:80"