version: "3"

services:
    bolt:
        image: rossriley/docker-bolt:mysql-3.5
        volumes:
            - ./app:/var/www/html/app
            - ./public:/var/www/html/public
            - ./extensions:/var/www/html/extensions
            - ./config/php.ini:/usr/local/etc/php/conf.d/custom.ini
        ports:
            - "127.0.0.1:8000:80"
        env_file:
            - config/bolt.env
        links:
            - mariadb
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}

    mariadb:
        image: mariadb:latest
        restart: always
        env_file:
            - config/mariadb.env
        volumes:
            - ./mysql:/var/lib/mysql
            - ./config/mariadb-init:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    # adminer:
    #     image: dockette/adminer:mysql
    #     restart: always
    #     ports:
    #         - "127.0.0.1:8008:80"